# AzureDevOps Pipeline for deploying SAM lambdas to AWS
# Mike Zazon
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - /*

stages:
- stage: BuildAndPublish
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      matrix:
        Python37:
          python.version: '3.7'
    steps:
    - template: build-lambda-sam-template.yml
      parameters:
        awsCredentials: 'aws-ss-prod-acct'
        regionName: 'us-east-2'
        lambdaProjectPath: 'template.yml'
        s3bucket: 'mz-us-east-2-sam-deploy'
- stage: DeployToAWSDev
  jobs:
#      matrix:
#        Python37:
#          python.version: '3.7'
  - deployment: DeployToAWSDev
    pool:
      vmImage: 'ubuntu-latest'
    displayName: 'Deploy to AWS Dev'
    environment: 'aws-ss-prod-acct'
    strategy:
        runOnce:
          deploy:
            steps:
            - download: none
            - template: deploy-lambda-sam-template.yml
              parameters:
                awsCredentials: 'aws-ss-prod-acct'
                regionName: 'us-east-2'
                s3bucket: 'mz-us-east-2-sam-deploy'
                stackName: 'aws-sam-hello-world-alb'
#- stage: ValidateDevEndpointDeployment
#  jobs:
#  - job: TestDevAPIGatewayEndpoint
#    pool:
#      vmImage: 'ubuntu-latest'
#    steps:
#    - bash: curl -sSf https://4uoiq58czl.execute-api.us-east-2.amazonaws.com/Prod/api/S3Proxy
